package com.example.ltx.orm_greendao.db.entity;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.ltx.orm_greendao.db.entity.User;
import com.example.ltx.orm_greendao.db.entity.NetCache;

import com.example.ltx.orm_greendao.db.entity.UserDao;
import com.example.ltx.orm_greendao.db.entity.NetCacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig netCacheDaoConfig;

    private final UserDao userDao;
    private final NetCacheDao netCacheDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        netCacheDaoConfig = daoConfigMap.get(NetCacheDao.class).clone();
        netCacheDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        netCacheDao = new NetCacheDao(netCacheDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(NetCache.class, netCacheDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        netCacheDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public NetCacheDao getNetCacheDao() {
        return netCacheDao;
    }

}
